### ISSUE TITLE
Error during installation of R package

### ISSUE THREAD

**Issue by ibulanov** [shahcompbio/Epiclomal#3]
Hi there,

During the installation I got the error about 54 line of epiclomal_function.cpp:

`if (isnan(mean)) imputed_data(*idx, i) = NA_REAL;`

Only when I changed to:

`if (std::isnan(mean)) imputed_data(*idx, i) = NA_REAL;`

The package was compiled and installed sucessfully.

Not a open issue for me, but can you please edit it? Maybe for somebody it would save a time.

I ddin't specify exact error log, my apologies.

Kind regards,
Igor

**Comment by mandronescu** [comment]
Dear Igor,

Thank you so much for your feedback, I appreciate it!
I have now added your suggestion in the code.

All the best,
Mirela.


On Aug 17, 2020, at 1:41 AM, Igor Bulanov <notifications@github.com<mailto:notifications@github.com>> wrote:


This email came from an EXTERNAL SENDER. If you think this message is suspicious, please do not open any attached files or links, and forward it as an attachment to spammail@bccrc.ca<mailto:spammail@bccrc.ca>




Hi there,

During the installation I got the error about 54 line of epiclomal_function.cpp:

if (isnan(mean)) imputed_data(*idx, i) = NA_REAL;

Only when I changed to:

if (std::isnan(mean)) imputed_data(*idx, i) = NA_REAL;

The package was compiled and installed sucessfully.

Not a open issue for me, but can you please edit it? Maybe for somebody it would save a time.

I ddin't specify exact error log, my apologies.

Kind regards,
Igor
