### ISSUE TITLE
regions.txt file is an input .. or output of the first part of snakemake

### ISSUE THREAD

**Issue by neuroedge** [shahcompbio/Epiclomal#7]
Hi, 
Thanks for this fascinating work! I'm trying to get this to work on my own single-cell dataset.

I don't think this is a real coding issue, but perhaps something unclear in the instructions...

As I understand it, the process_real_data is the first part, while the real_data is the second part.
In the first part, process_real_data, the input is takes .coverage files from Bismark... and the output is regions.txt file and also methylation format specifically made by Epiclomal.

So, I am confused why I am running into an error when I leave the path to REGION_FILE as something non-existent in my config.yaml.

Below, I modified the config.yaml in Epiclomal/snakemake/process_real_data as below, thinking that the regions.txt file will be produced..

REGION_FILE: 'mydata/regions.txt.gz'

When I run it I have this error message.
(Epiclomal) $ ./run.sh
Building DAG of jobs...
MissingInputException in line 53 of /data1/chongw/Epiclomal/snakemake/process_real_data/Snakefile:
Missing input files for rule get_cpgs_in_regions:
mydata/regions.txt.gz

Thanks!

**Comment by Emilianopp** [comment]
REGION_FILE: should be an input indicating the start and end as well as the chr.
ie:
```
chr	start	end

chr1	1	25621
```

**Comment by neuroedge** [comment]
Thank you! I think this solved the problem, it led to another error output but as you know I've been in contact via email. So for this specific issue, i'm going to mark as closed. Thanks!
